# source for this config is
# https://jekyllrb.com/docs/continuous-integration/travis-ci/
#
sudo: false
matrix:
  include:
    - language: ruby
      rvm:
        - 2.6.0
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
      cache: bundler # caching bundler gem packages will speed up build
      before_script:
        - chmod +x ./build-tools/ci-build.sh # or do this locally and commit
      script:
        - ./build-tools/ci-build.sh

    - language: node_js
      node_js:
        - 10.15.3
      cache: npm
      install:
        - npm ci

      script:
        - npm run build
