markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  parse_block_html: true
  footnote_backlink: '↑'
  syntax_highlighter: rouge
highlighter: rouge
host: 0.0.0.0
exclude: [ignore,user.fabiantheblind.espressostorage,Project.espressostorage,bower_components,node_modules,vendor]
sass:
    sass_dir: assets/_sass
    style: compressed
# baseurl: /
paginate: 5
paginate_path: "blog/page:num"

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
# own variables
#
url: https://fabianmoronzirfas.me
name: "fabianmoronzirfas.me"
title: "Fabian Morón Zirfas on the web"