markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  parse_block_html: true
  footnote_backlink: '↑'
  syntax_highlighter: rouge
highlighter: rouge
host: 0.0.0.0
exclude: [ignore,user.fabiantheblind.espressostorage,Project.espressostorage,bower_components,node_modules]
sass:
    sass_dir: assets/_sass
    style: compressed
# baseurl: /
paginate: 5
paginate_path: "blog/page:num"

plugins: [jekyll-paginate]
# own variables
#
name: "fabianmoronzirfas.me"
title: "Fabian Morón Zirfas on the web"